import type { Metadata } from "next";
import localFont from "next/font/local";
import {Jersey_25} from 'next/font/google'
import "./globals.css";

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const jersey = Jersey_25({
  variable: "--font-geist-mono",
  weight: '400',
  subsets: ["latin"]
});
export const metadata: Metadata = {
  title: "RetroVibes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
      <body
        className={`${jersey.variable} ${geistMono.variable} overflow-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
